Repository GoogleCloudPlatform/gsutil, pull requests merged in 2019-05, with the labels that each got.

#766 XML >1k buckets test flake fix
  gslib/tests/test_stat.py
  gslib/tests/test_tabcomplete.py
  gslib/tests/testcase/base.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes, test

#767 Fix flaky integ test on Windows
  gslib/tests/test_ui.py
Labels: cla: yes, test

#773 Fix rm wildcard bug with >1,000 buckets
  gslib/tests/test_rm.py
Labels: bug, cla: yes, test

#772 Fix Iam Bucket URL Regex
  gslib/commands/iam.py
  gslib/utils/text_util.py
Labels: bug, cla: yes

#774 Fixed integ test for 'cp -L' flag
  gslib/tests/test_cp.py
Labels: cla: yes, test

#775 Added time elapsed to 'Still running' messages.
  gslib/commands/test.py
Labels: cla: yes, logging, test

#778 Remove use of the term "subdirectories".
  gslib/commands/mv.py
Labels: cla: yes, documentation

#780 Remove use of "global" in KMS key examples
  gslib/commands/kms.py
Labels: cla: yes, documentation

#782 Update code example in throttling.py
  gslib/addlhelp/throttling.py
Labels: cla: yes

#783 Make signurl work with objects containing tildes.
  gslib/commands/signurl.py
Labels: Python 2/3 Compat, bug, cla: yes

#784 Small doc edits
  gslib/commands/bucketpolicyonly.py
  gslib/commands/cp.py
  gslib/commands/notification.py
Labels: cla: yes

#785 Link fix in cp.py
  gslib/commands/cp.py
Labels: cla: yes

#786 Improve logic for detecting PKCS 12 keys
  gslib/gcs_json_credentials.py
Labels: Python 2/3 Compat, bug, cla: yes

#789 Remove test dir from test_update
  gslib/commands/signurl.py
  gslib/tests/test_update.py
Labels: cla: yes, test

#792 Tab complete compatibility with 2.x and 3.x
  gslib/tests/testcase/integration_testcase.py
Labels: Python 2/3 Compat, bug, cla: yes
