Repository GoogleCloudPlatform/gsutil, pull requests merged in 2019-04, with the labels that each got.

#710 [CI] Fixed path to Windows build file
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#712 Reverting dependency changes from merge
  gsutil.py
  setup.py
Labels: CI, cla: yes

#717 Fixed test that wasn't explicity looking for bytes
  gslib/tests/test_cp.py
Labels: cla: yes

#716 Use compatibale six.moves.zip function
  gslib/commands/iam.py
Labels: Python 2/3 Compat, cla: yes

#718 Revised get_random_ascii_characters function
  gslib/utils/text_util.py
Labels: Python 2/3 Compat, cla: yes

#715 Updated integ tests for Python 3
  gslib/__main__.py
  gslib/tests/test_Doption.py
  gslib/utils/system_util.py
Labels: Python 2/3 Compat, cla: yes

#721 Decode filenames before creation
  gslib/tests/testcase/base.py
Labels: Python 2/3 Compat, bug, cla: yes

#719 Fix perfdiag tests that were hitting eof and causing failures
  .travis.yml
  gslib/boto_translation.py
Labels: cla: yes

#722 Remove newline concats to stdin
  gslib/tests/test_cp.py
  gslib/tests/testcase/integration_testcase.py
Labels: Python 2/3 Compat, bug, cla: yes, test

#711 Updated parameters passed to .ps1 script
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#723 Corrected regex matching in test output
  gslib/tests/test_Doption.py
Labels: Python 2/3 Compat, bug, cla: yes, test

#724 Improve output of Windows integration test script
  test/ci/kokoro/windows/run_integ_tests.ps1
Labels: cla: yes

#725 Broaden `MonkeyPatchHttp()` for additional versions of Python3
  gslib/utils/system_util.py
Labels: cla: yes

#729 Ensure manifest strings are decoded before writing
  gslib/utils/copy_helper.py
Labels: Python 2/3 Compat, cla: yes

#730 Refactored test_cp to decode strings
  gslib/tests/test_cp.py
  gslib/utils/copy_helper.py
Labels: Python 2/3 Compat, cla: yes

#731 Replaced 'utf-8' literals with constant var
  gslib/utils/text_util.py
Labels: cla: yes, cleanup

#728 Add host header support for JSON
  gslib/commands/config.py
  gslib/gcs_json_api.py
  gslib/tests/test_perfdiag.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#732 Ensure unicode for rsync temp file attributes
  gslib/commands/rsync.py
Labels: Python 2/3 Compat, bug, cla: yes

#736 CI readme file
  test/ci/CI.md
Labels: CI, cla: yes, documentation

#738 Contribution doc updates
  README.md
  gslib/addlhelp/dev.py
  test/ci/CI.md
Labels: CI, cla: yes, documentation

#739 Fixed path to Windows build file (#710)
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#740 Replaced 'utf-8' literals with constants.UTF8
  gslib/boto_resumable_upload.py
  gslib/commands/ls.py
  gslib/commands/perfdiag.py
  gslib/commands/test.py
  gslib/gcs_json_api.py
  gslib/gcs_json_media.py
  gslib/parallel_tracker_file.py
  gslib/pubsub_api.py
  gslib/resumable_streaming_upload.py
  gslib/tests/test_acl.py
  gslib/tests/test_bucketconfig.py
  gslib/tests/test_cors.py
  gslib/tests/test_cp.py
  gslib/tests/test_du.py
  gslib/tests/test_iam.py
  gslib/tests/test_label.py
  gslib/tests/test_naming.py
  gslib/tests/test_requester_pays.py
  gslib/tests/test_tracker_file.py
  gslib/tests/test_ui.py
  gslib/tests/test_update.py
  gslib/tests/testcase/base.py
  gslib/tests/testcase/integration_testcase.py
  gslib/tests/testcase/unit_testcase.py
  gslib/tests/util.py
  gslib/utils/boto_util.py
  gslib/utils/constants.py
  gslib/utils/hashing_helper.py
Labels: cla: yes, cleanup

#742 Fixes for Windows CI test wrapper
  test/ci/kokoro/windows/config_generator.bat
  test/ci/kokoro/windows/config_generator.ps1
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#745 [CI] Remove notification URL from config
  test/ci/kokoro/windows/config_generator.ps1
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#746 Ensure wildcard test objects are unicode
  gslib/tests/test_wildcard_iterator.py
Labels: CI, cla: yes

#747 Use io.open for private keyfile
  gslib/gcs_json_credentials.py
Labels: CI, cla: yes

#750 Link CORS command page to related GCS docs.
  gslib/commands/cors.py
Labels: cla: yes

#749 Allow configuring compression level
  gslib/commands/config.py
  gslib/utils/copy_helper.py
Labels: cla: yes

#753 Permission fix for config_generator.sh
  test/ci/kokoro/config_generator.sh
  test/ci/kokoro/run_integ_tests.sh
Labels: CI, cla: yes

#755 Apply HTTP monkey patch to Python 3.7.0
  gslib/utils/system_util.py
Labels: CI, bug, cla: yes

#757 Updated version support comment
  gslib/utils/system_util.py
Labels: cla: yes, cleanup

#758 Fix setup.py to not package test and boto bloat.
  MANIFEST.in
  setup.py
Labels: cla: yes, cleanup

#760 Removed duplicate test runners
  test/RunParallelTestsOnWindows.ps1
  test/ci/kokoro/linux/run_integ_tests.sh
  test/ci/kokoro/macos/run_integ_tests.sh
Labels: cla: yes, cleanup

#762 Acl doc updates
  gslib/commands/acl.py
  gslib/commands/defacl.py
Labels: cla: yes

#761 Get GID for -P tests from dest dir
  gslib/tests/test_cp.py
  gslib/tests/test_rsync.py
  gslib/tests/util.py
Labels: CI, bug, cla: yes, test

#764 Removed flaky assert
  gslib/tests/test_ui.py
Labels: bug, cla: yes, test

#765 Don't test blank ls command for S3 test mode.
  gslib/tests/test_ls.py
Labels: cla: yes, test
