Repository GoogleCloudPlatform/gsutil, pull requests merged in 2019-03, with the labels that each got.

#641 Update TravisCI to use Xenial (Ubuntu 16.04)
  .travis.yml
Labels: cla: yes

#642 Added Kokoro integration test scripts.
  test/ci/kokoro/linux/continuous.sh
  test/ci/kokoro/linux/presubmit.sh
  test/ci/kokoro/linux/run_integ_tests.sh
  test/ci/kokoro/macos/continuous.sh
  test/ci/kokoro/macos/presubmit.sh
  test/ci/kokoro/macos/run_integ_tests.sh
Labels: cla: yes

#643 Added config generator for CI test scripts.
  test/ci/kokoro/config_generator.sh
Labels: cla: yes

#644 Added build configs, removed symlinks.
  test/ci/kokoro/linux/continuous.sh
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/linux/presubmit.sh
  test/ci/kokoro/macos/continuous.sh
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/macos/presubmit.sh
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/run_integ_tests.ps1
Labels: cla: yes

#646 Spacing fixes for docs, based on last release.
  gslib/addlhelp/encoding.py
  gslib/addlhelp/wildcards.py
  gslib/commands/mb.py
  gslib/commands/notification.py
  gslib/commands/rsync.py
Labels: cla: yes

#649 Added details for Bucket Policy Only for defacl get.
  gslib/command.py
Labels: cla: yes

#648 Kokoro builds now fetch keys from Keystore
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/windows/presubmit.cfg
Labels: cla: yes

#651 Added param configs for Kokoro Windows jobs
  test/ci/kokoro/windows/presubmit.cfg
Labels: cla: yes

#647 Explicit wording in rm docs about deleting buckets
  gslib/commands/rm.py
Labels: cla: yes

#654 Fix docs formatting to convert to better HTML.
  gslib/commands/acl.py
  gslib/commands/bucketpolicyonly.py
  gslib/commands/mb.py
  gslib/commands/requesterpays.py
  gslib/commands/retention.py
  gslib/commands/versioning.py
Labels: cla: yes

#656 Additional checks around ShouldProhibitMultiprocessing()
  gslib/utils/parallelism_framework_util.py
Labels: cla: yes

#659 Updated Kokoro build script paths.
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/windows/presubmit.cfg
Labels: CI, cla: yes

#660 Catch up CI testing branch with master
  gslib/commands/acl.py
  gslib/commands/bucketpolicyonly.py
  gslib/commands/mb.py
  gslib/commands/requesterpays.py
  gslib/commands/retention.py
  gslib/commands/rm.py
  gslib/commands/versioning.py
  gslib/utils/parallelism_framework_util.py
Labels: CI, cla: yes

#661 Python 3 compatibility fixes in TestCp
  gslib/gcs_json_media.py
  gslib/tests/test_cp.py
  gslib/tests/test_update.py
  gslib/tests/testcase/base.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#662 DU Fixes
  gslib/commands/du.py
  gslib/utils/ls_helper.py
Labels: cla: yes

#664 Cleanup
  gslib/commands/du.py
  gslib/tests/test_cp.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#668 Updated keystore key name
  test/ci/kokoro/linux/continuous.cfg
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/macos/continuous.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
Labels: CI, bug, cla: yes

#670 Update storage_v1_* apitools generated modules.
  gslib/third_party/storage_apitools/storage_v1_client.py
  gslib/third_party/storage_apitools/storage_v1_messages.py
Labels: cla: yes

#671 Encoding for win
  gslib/commands/version.py
  gslib/utils/text_util.py
Labels: cla: yes

#672 Added configs for child jobs
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#673 du windows fixes - text encoding
  gslib/commands/du.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#674 Du comment changes
  gslib/commands/du.py
Labels: cla: yes

#675 Newline added in Win/Py3 with CSV writer issue fixed.
  gslib/utils/copy_helper.py
Labels: cla: yes

#677 Removed `type` and `group_spec` from build configs
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, bug, cla: yes

#678 Prepended continuous config to child configs
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, bug, cla: yes

#679 Updating build script path to a relative path.
  test/ci/kokoro/linux/continuous.cfg
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/continuous.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, bug, cla: yes

#680 Relative path updated to not use ./
  test/ci/kokoro/linux/continuous.cfg
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/continuous.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, bug, cla: yes

#683 Metrics Test Fixes for Windows / py3
  gslib/metrics.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#682 Add support for conditions in IAM policy bindings.
  gslib/commands/config.py
  gslib/commands/iam.py
  gslib/exception.py
  gslib/tests/test_iam.py
  gslib/tests/testcase/integration_testcase.py
  gslib/third_party/storage_apitools/storage_v1_messages.py
Labels: cla: yes

#684 Typo fixes
  gslib/commands/rsync.py
Labels: cla: yes

#685 Updated .boto config path in environment variables.
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#686 Print trace in debug mode for rsync sync failures
  gslib/commands/rsync.py
Labels: cla: yes

#689 Update limits on compose operations
  gslib/commands/compose.py
Labels: cla: yes

#690 Fix description of the progress indicator bar
  gslib/commands/cp.py
Labels: cla: yes

#688 Bunch of small doc fixes.
  gslib/addlhelp/prod.py
  gslib/addlhelp/versions.py
  gslib/commands/acl.py
  gslib/commands/cp.py
  gslib/commands/stat.py
  gslib/commands/versioning.py
  gslib/commands/web.py
Labels: cla: yes

#691 Removed `allow_failures` for python 3 tests
  .travis.yml
Labels: cla: yes

#695 Updated Mac and Linux CI scripts and configs to working status.
  test/ci/kokoro/config_generator.sh
  test/ci/kokoro/linux/continuous.cfg
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/linux/run_integ_tests.sh
  test/ci/kokoro/macos/continuous.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/macos/run_integ_tests.sh
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#697 Export BOTO_PATH environment variable
  test/ci/kokoro/linux/run_integ_tests.sh
Labels: CI, cla: yes

#700 [CI TESTING] Added .bat script for Windows tests
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#701 Python exe path computed at runtime
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#702 Remove note about object composition limits.
  gslib/commands/cp.py
Labels: cla: yes

#703 Removed BOTO_CONFIG from Windows *.cfg
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes

#704 Fix indentation in `iam` command synopsis.
  gslib/commands/iam.py
Labels: cla: yes

#705 Added Windows config generator, build wrapper
  test/ci/kokoro/windows/config_generator.bat
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
  test/ci/kokoro/windows/run_integ_tests.bat
Labels: CI, cla: yes

#706 Moved Linx / Mac build file up a dir, removed symlink
  test/ci/kokoro/linux/continuous.cfg
  test/ci/kokoro/linux/presubmit.cfg
  test/ci/kokoro/linux/py27_json.cfg
  test/ci/kokoro/linux/py27_xml.cfg
  test/ci/kokoro/linux/py35_json.cfg
  test/ci/kokoro/linux/py35_xml.cfg
  test/ci/kokoro/linux/py36_json.cfg
  test/ci/kokoro/linux/py36_xml.cfg
  test/ci/kokoro/linux/py37_json.cfg
  test/ci/kokoro/linux/py37_xml.cfg
  test/ci/kokoro/macos/continuous.cfg
  test/ci/kokoro/macos/presubmit.cfg
  test/ci/kokoro/macos/py27_json.cfg
  test/ci/kokoro/macos/py27_xml.cfg
  test/ci/kokoro/macos/py35_json.cfg
  test/ci/kokoro/macos/py35_xml.cfg
  test/ci/kokoro/macos/py36_json.cfg
  test/ci/kokoro/macos/py36_xml.cfg
  test/ci/kokoro/macos/py37_json.cfg
  test/ci/kokoro/macos/py37_xml.cfg
  test/ci/kokoro/macos/run_integ_tests.sh
  test/ci/kokoro/run_integ_tests.sh
  test/ci/kokoro/windows/continuous.cfg
  test/ci/kokoro/windows/presubmit.cfg
  test/ci/kokoro/windows/py27_json.cfg
  test/ci/kokoro/windows/py27_xml.cfg
  test/ci/kokoro/windows/py35_json.cfg
  test/ci/kokoro/windows/py35_xml.cfg
  test/ci/kokoro/windows/py36_json.cfg
  test/ci/kokoro/windows/py36_xml.cfg
  test/ci/kokoro/windows/py37_json.cfg
  test/ci/kokoro/windows/py37_xml.cfg
Labels: CI, cla: yes
