Repository GoogleCloudPlatform/gsutil, pull requests merged in 2019-06, with the labels that each got.

#798 Add debugging mechanisms and fix tabcomplete tests.
  gslib/__main__.py
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes

#799 Skip test while svc-side functionality is broken.
  gslib/tests/test_notification.py
Labels: cla: yes

#801 Typo fix
  gslib/__main__.py
Labels: Python 2/3 Compat, bug, cla: yes

#802 Sanitize writes to FDs
  gslib/tests/testcase/unit_testcase.py
Labels: cla: yes

#805 Update rsync.py
  gslib/commands/rsync.py
Labels: cla: yes

#808 Fix update command; allow detection of yapf files.
  gslib/utils/update_util.py
Labels: bug, cla: yes

#796 Test `help` command for all commands.
  gslib/tests/test_help.py
Labels: cla: yes

#810 Add file with whitespace in name to rsync tests
  gslib/tests/test_rsync.py
  gslib/tests/test_update.py
Labels: cla: yes, test

#781 Adding location type to ls command and JSON API
  gslib/commands/ls.py
  gslib/tests/test_ls.py
  gslib/third_party/storage_apitools/storage_v1_messages.py
Labels: cla: yes

#814 Replace sys.stderr.write with print_to_fd
  gslib/tests/testcase/unit_testcase.py
Labels: bug, cla: yes

#815 Fix unconverted markup to look better for web docs
  gslib/commands/iam.py
Labels: cla: yes

#816 Skip a test that's currently failing for...
  gslib/tests/test_ls.py
Labels: cla: yes

#818 Sort the boto auth handlers in our patched method.
  gslib/utils/boto_util.py
Labels: cla: yes

#822 Made resumable upload test use bigger file
  gslib/tests/test_cp.py
Labels: bug, cla: yes, test

#821 Add test for setting request reason into x-goog-request-reason. Tracking bug: b/131747209
  gslib/tests/test_cp.py
Labels: cla: yes, test

#824 Add process timeout for tests
  gslib/tests/testcase/integration_testcase.py
Labels: cla: yes, test

#825 Added retry decorators to more tests
  gslib/tests/test_cp.py
  gslib/tests/test_iam.py
  gslib/tests/test_rsync.py
Labels: cla: yes, test

#826 Prefix invalid tabcomplete bucket name
  gslib/tests/test_tabcomplete.py
  gslib/tests/testcase/base.py
Labels: bug, cla: yes, test

#827 Adjust wildcard bucket names
  gslib/tests/test_cors.py
  gslib/tests/test_ls.py
Labels: cla: yes, test

#828 Add x-goog-request-reason
  gslib/boto_translation.py
  gslib/gcs_json_api.py
  gslib/tests/test_cp.py
  gslib/utils/constants.py
Labels: cla: yes

#830 Move retry decorators into nested functions
  gslib/tests/test_cors.py
  gslib/tests/test_cp.py
  gslib/tests/test_iam.py
  gslib/tests/test_rsync.py
Labels: bug, cla: yes, test

#832 Updated hex conversions
  gslib/tests/test_util.py
  gslib/utils/text_util.py
Labels: bug, cla: yes

#835 Fix broken _UrlEncode(), improve docs, add tests.
  gslib/commands/rsync.py
  gslib/tests/test_rsync.py
Labels: cla: yes

#838 Make quote_plus behave the same on Python 2 and 3.
  gslib/commands/rsync.py
  gslib/tests/test_rsync.py
Labels: cla: yes

#837 Make quote_plus behave the same on Python 2 and 3.
  gslib/commands/rsync.py
  gslib/tests/test_rsync.py
Labels: cla: yes

#840 S3 py3 fixes
  gslib/tests/test_label.py
  gslib/utils/copy_helper.py
Labels: Python 2/3 Compat, cla: yes, test
